index: # Je choisis le nom de ma route ./!\ pas de doublon.
    path: / # Ma route
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

